language: cpp
sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - 

  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - ninja-build
    - qtbase5-dev

before_install:
  - |
    # Install cmake
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      cd /tmp
      mkdir cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=/tmp/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - |
    # Install cmake and ninja
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export QTDIR=/usr/lib/x86_64-linux-gnu/qt5
      export PATH="$QTDIR/bin:$PATH"
    else
      brew update > /dev/null
      brew tap homebrew/versions
      brew install ninja
      brew install qt
      export QTDIR="/usr/local/opt/qt5"
      export PATH="$QTDIR/bin:$PATH"
    fi

install:
# Clone examples: they are the code to test against.
  - git clone git@github.com:frederikvannoote/cmake-common-examples.git ${HOME}/examples
  - export CMAKE_COMMON=${TRAVIS_BUILD_DIR}
  - mkdir /tmp/installed

script:  
  - mkdir /tmp/simplelib-build
  - cd /tmp/simplelib-build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -G Ninja ${HOME}/examples/simplelib
  - cmake --build . --target all
  - cmake --build . --target install
  - cmake --build . --target sdk
# Relocate library
  - cp -r /tmp/installed /tmp/relocated
 
  - mkdir /tmp/simpleapp-build
  - cd /tmp/simpleapp-build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -DCC1simplelib_DIR=/tmp/relocated/lib/cmake/CC1simplelib -G Ninja ${HOME}/examples/simpleapp
  - cmake --build . --target all
  - cmake --build . --target install

  - mkdir /tmp/QSimpleApp-build
  - cd /tmp/QSimpleApp-build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -DCC1simplelib_DIR=/tmp/relocated/lib/cmake/CC1simplelib -G Ninja ${HOME}/examples/QSimpleApp/
  - cmake --build . --target all
  - cmake --build . --target install

  - mkdir /tmp/complexlib-build
  - cd /tmp/complexlib-build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -G Ninja ${HOME}/examples/complexlib
  - cmake --build . --target all
  - cmake --build . --target install
  - cmake --build . --target sdk

